### ISSUE TITLE
Move Yurimaguas to a new state

### ISSUE THREAD

**Issue by Idhrendur** [Idhrendur/RomanHoI4#10]
Given the plausible English war aims, move this Andean province to an Andean state.

**Comment by CaesarVincens** [comment]
I believe I have done this, I reconfigured Ica and Lima so that Lima is coastal Andes and Ica is Amazonian Andes. Will check Vic2 provinces to see if more needs to be done.

**Comment by CaesarVincens** [comment]
I moved these provinces to the state north of Lima (Cajamarca?)
