### ISSUE TITLE
Divide Scandinavian states

### ISSUE THREAD

**Issue by Idhrendur** [Idhrendur/RomanHoI4#4]
The way the cores and cultures work out, Goteburg and Malmo should both be split into their Norwegian and Swedish halves.

**Comment by CaesarVincens** [comment]
I can do this directly for HoI4. I'll compare the Vic2 states to see roughly where to split it.

**Comment by CaesarVincens** [comment]
I have split Malmo and Goteburg as well as Finnish and Russian core Karelia (both held by Scandinavia).

**Comment by CaesarVincens** [comment]
This is long completed
