### ISSUE TITLE
Adjust South East Asian states

### ISSUE THREAD

**Issue by Idhrendur** [Idhrendur/RomanHoI4#8]
- The provinces owned by Siam should either be moved into a new state or moved into Ayutthaya.
- Chaing Mai and Nan should be moved into a new state.
- Cham's two provinces in Hue should be split into their own state.
- Pattani's provinces should be moved into a single state.

**Comment by CaesarVincens** [comment]
I can take care of these in HoI4 more easily I think. I've already planned on some

**Comment by CaesarVincens** [comment]
I've started working on this, I've adjusted several Indian states to reflect the Vic2 cores, more work needs to be done.

More specifically, I can adjust and create new states as needed to match up province cores from Vic2
